import {
  Brain, BookOpen, FileCode, Trash2, Terminal, Package, Server,
  RefreshCw, Database, GitBranch, Rocket, Camera, Monitor, Eye,
  ScrollText, Zap, Link, Lock, Bug, FlaskConical, Activity,
  Search, Key, GitCommit, ShieldCheck, FileSearch, Replace, StopCircle,
} from "lucide-react";

export const TOOL_ICON_MAP: Record<string, React.ElementType> = {
  "analysis.think":          Brain,
  "file_list":               BookOpen,
  "file_read":               BookOpen,
  "file_write":              FileCode,
  "file_delete":             Trash2,
  "file_search":             FileSearch,
  "file_replace":            Replace,
  "shell_exec":              Terminal,
  "package_install":         Package,
  "package_uninstall":       Package,
  "detect_missing_packages": Package,
  "server_start":            Server,
  "server_stop":             StopCircle,
  "server_restart":          RefreshCw,
  "server_logs":             ScrollText,
  "preview_url":             Eye,
  "preview_screenshot":      Camera,
  "env_read":                Key,
  "env_write":               Key,
  "git_status":              GitBranch,
  "git_add":                 GitBranch,
  "git_commit":              GitCommit,
  "git_clone":               GitBranch,
  "git_push":                GitBranch,
  "git_pull":                GitBranch,
  "db_push":                 Database,
  "db_migrate":              Database,
  "deploy_publish":          Rocket,
  "test_run":                FlaskConical,
  "debug_run":               Bug,
  "monitor_check":           Activity,
  "browser_eval":            Monitor,
  "api_call":                Link,
  "search_web":              Search,
  "auth_login":              Lock,
  "package_audit":           ShieldCheck,
  "task_complete":           Zap,
  "agent_message":           Brain,
  "agent_question":          Brain,
};

export const TOOL_COLOR_MAP: Record<string, string> = {
  "analysis.think":          "#3b82f6",
  "file_list":               "#7dd3fc",
  "file_read":               "#7dd3fc",
  "file_write":              "#22c55e",
  "file_delete":             "#ef4444",
  "file_search":             "#22d3ee",
  "file_replace":            "#22c55e",
  "shell_exec":              "#f59e0b",
  "package_install":         "#f97316",
  "package_uninstall":       "#f97316",
  "detect_missing_packages": "#f97316",
  "server_start":            "#22c55e",
  "server_stop":             "#ef4444",
  "server_restart":          "#f97316",
  "server_logs":             "#94a3b8",
  "preview_url":             "#a78bfa",
  "preview_screenshot":      "#a78bfa",
  "env_read":                "#f59e0b",
  "env_write":               "#f59e0b",
  "git_status":              "#22c55e",
  "git_add":                 "#22c55e",
  "git_commit":              "#22c55e",
  "git_clone":               "#22c55e",
  "git_push":                "#22c55e",
  "git_pull":                "#22c55e",
  "db_push":                 "#34d399",
  "db_migrate":              "#34d399",
  "deploy_publish":          "#3b82f6",
  "test_run":                "#34d399",
  "debug_run":               "#ef4444",
  "monitor_check":           "#3b82f6",
  "browser_eval":            "#94a3b8",
  "api_call":                "#38bdf8",
  "search_web":              "#f97316",
  "auth_login":              "#f59e0b",
  "package_audit":           "#818cf8",
  "task_complete":           "#22c55e",
  "agent_message":           "#3b82f6",
  "agent_question":          "#3b82f6",
};
