export type { FileNode, RawTreeNode, ContextMenuState } from "./types";
export { fileIcon, guessLang, emojiIcon }               from "./file-icon";
export { uid, flattenFiles, deleteNodeById, renameNodeById, addNodeToRoot, makeInitialTree } from "./tree-helpers";
export { InlineInput, ActionIcon }                      from "./InlineInput";
export { TreeNode }                                     from "./TreeNode";
export { FileTreePanel }                                from "./FileTreePanel";
export { ContextMenu }                                  from "./ContextMenu";
export { useFileExplorer }                              from "./use-file-explorer";
export { useOpenEditors }                               from "./use-open-editors";
export { useRecentFiles }                               from "./use-recent-files";
export { useAgentStatus }                               from "./use-agent-status";
export type { AgentStatus, AgentId, AgentState }        from "./use-agent-status";
export { OpenEditorsPanel }                             from "./OpenEditorsPanel";
export { AgentStatusPanel }                             from "./AgentStatusPanel";
export { AIActivityBadge }                              from "./AIActivityBadge";
export { default as FileExplorer }                      from "./FileExplorer";
export { default as FileHistoryPanel }                  from "./FileHistoryPanel";
