export type {
  HvpLayer,
  NodeRole,
  ImportType,
  BoundaryViolationType,
  ValidationPhase as BoundaryValidationPhase,
  ArchNode,
  ArchEdge,
  ArchitectureGraph,
  BoundaryViolation,
  LayerValidationResult,
  DirectionValidationResult,
  DomainLeakageResult,
  BoundaryReport,
  BoundarySession,
  IntermediateViolations,
  ViolationSeverity as BoundaryViolationSeverity,
} from "./structural/boundary-analysis/index.js";
export {
  BOUNDARY_SCORE_START,
  MAX_BOUNDARY_VIOLATIONS,
  BOUNDARY_DEDUCTIONS,
  HVP_ALLOWED_DIRECTIONS,
  FORBIDDEN_DOMAIN_PAIRS,
  INFRASTRUCTURE_DOMAINS,
  analyzeBoundaries,
  analyzeMultiple as analyzeBoundaryMultiple,
  getLastReport as getLastBoundaryReport,
  getReportHistory as getBoundaryReportHistory,
  resetAnalyzer as resetBoundaryAnalyzer,
} from "./structural/boundary-analysis/index.js";

export type {
  AnalysisPhase as DependencyAnalysisPhase,
  CouplingRisk,
  EdgeKind,
  SourceModule,
  DependencyInput,
  GraphNode,
  GraphEdge,
  DependencyGraph,
  CycleGroup,
  CouplingScore,
  DependencyCluster,
  DependencyMetrics,
  DependencyAnalysisResult,
  DependencySession,
} from "./structural/dependency-analysis/index.js";
export {
  MAX_MODULES,
  MAX_CYCLES_REPORTED,
  INSTABILITY_HIGH_RISK,
  INSTABILITY_MED_RISK,
  LARGE_CYCLE_THRESHOLD,
  HEALTH_SCORE_START,
  HEALTH_DEDUCTIONS,
  analyzeDependencies,
  analyzeMultiple as analyzeDependencyMultiple,
  getLastResult as getLastDependencyResult,
  getResultHistory as getDependencyResultHistory,
  resetAnalyzer as resetDependencyAnalyzer,
} from "./structural/dependency-analysis/index.js";

export type {
  ConcernTag,
  ViolationSeverity as SrpViolationSeverity,
  SRPViolationType,
  AnalysisPhase as SrpAnalysisPhase,
  FileRole as SrpFileRole,
  FileDescriptor,
  ConcernEvidence,
  ConcernDetection,
  ResponsibilityViolation,
  SRPScore,
  PurityScore,
  ResponsibilityReport,
  ProjectFiles,
  ResponsibilitySession,
  IntermediateAnalysis,
} from "./structural/responsibility-analysis/index.js";
export {
  LINE_COUNT_THRESHOLD,
  CONCERN_MIX_THRESHOLD,
  SRP_PERFECT_SCORE,
  VIOLATION_DEDUCTIONS,
  analyzeResponsibility,
  analyzeMultiple as analyzeResponsibilityMultiple,
  getLastReport as getLastResponsibilityReport,
  getReportHistory as getResponsibilityReportHistory,
  resetAnalyzer as resetResponsibilityAnalyzer,
} from "./structural/responsibility-analysis/index.js";

export type {
  FileRole as HvpFileRole,
  ViolationSeverity as HvpViolationSeverity,
  ViolationType as HvpViolationType,
  ValidationPhase as HvpValidationPhase,
  LayerDefinition,
  FileNode,
  ImportEdge,
  Violation as HvpViolation,
  LayerReport,
  HVPComplianceReport,
  ProjectStructure,
  HVPAnalysisSession,
  IntermediateImportGraph,
  ValidatorResult,
} from "./structural/hvp-analysis/index.js";
export {
  HVP_DEFAULT_LAYERS,
  SCORE_DEDUCTIONS,
  MAX_REPORT_VIOLATIONS,
  analyzeHVP,
  analyzeMultiple as analyzeHvpMultiple,
  getLastReport as getLastHvpReport,
  getReportHistory as getHvpReportHistory,
  resetAnalyzer as resetHvpAnalyzer,
} from "./structural/hvp-analysis/index.js";

export * from "./structural/pattern-detection/index.js";
export {
  buildDecisionPlan,
  getDecisionState,
} from "./engine/arch-resolver/index.js";
export type {
  ArchitectureAnalysisReport as ArchResolverReport,
  AnalysisViolation as ArchResolverViolation,
  Decision,
  DecisionPlan,
  DecisionState,
  PriorityLevel,
  ViolationCategory,
} from "./engine/arch-resolver/index.js";
export * from "./engine/evolution/index.js";
export * from "./engine/architecture-fixer/index.js";

export type {
  PerformanceIssueType,
  PerformancePhase,
  CodeLanguage,
  CodeFile,
  PerformanceIssue,
  N1DetectionResult,
  MemoryLeakResult,
  AsyncMisuseResult,
  DbHotspotResult,
  IntermediateIssues,
  PerformanceReport,
  PerformanceSession,
} from "./code-quality/performance-analysis/index.js";
export {
  PERF_SCORE_START,
  MAX_PERF_ISSUES,
  PERF_DEDUCTIONS,
  DB_CALL_PATTERNS,
  MEMORY_LEAK_PATTERNS,
  ASYNC_MISUSE_PATTERNS,
  N1_LOOP_PATTERNS,
  DB_HOTSPOT_THRESHOLD,
  CRITICAL_HOTSPOT_THRESHOLD,
  analyzePerformance,
  analyzeMultipleProjects,
  resetAnalyzer as resetPerformanceAnalyzer,
} from "./code-quality/performance-analysis/index.js";

export type {
  SecurityIssueType,
  SecuritySeverity,
  SecurityPhase,
  SecurityCodeFile,
  SecurityIssue,
  AuthEnforcementResult,
  SecretsDetectionResult,
  InjectionScanResult,
  RbacValidationResult,
  IntermediateSecurityIssues,
  SecurityReport,
  SecuritySession,
} from "./security/security-analysis/index.js";
export {
  SEC_SCORE_START,
  MAX_SEC_ISSUES,
  SEC_DEDUCTIONS,
  AUTH_MIDDLEWARE_PATTERNS,
  ROUTE_DEFINITION_PATTERNS,
  SECRET_PATTERNS,
  SQL_INJECTION_PATTERNS,
  XSS_PATTERNS,
  COMMAND_INJECTION_PATTERNS,
  PATH_TRAVERSAL_PATTERNS,
  RBAC_ROLE_CHECK_PATTERNS,
  ADMIN_ENDPOINT_PATTERNS,
  analyzeSecurity,
  analyzeSecurityMultiple,
  getLastSecurityReport,
  getSecurityReportHistory,
  resetSecurityAnalyzer,
} from "./security/security-analysis/index.js";

export type {
  ApiContractIssueType,
  ContractSeverity,
  ApiContractPhase,
  HttpMethod,
  VersioningStrategy,
  ApiEndpoint,
  ApiContractIssue,
  EndpointConsistencyResult,
  SchemaValidationResult as ApiSchemaValidationResult,
  VersioningCheckResult,
  BreakingChangeResult,
  IntermediateContractIssues,
  ApiContractReport,
  ApiContractSession,
  ApiCodeFile,
} from "./data-and-api/api-contract-analysis/index.js";
export {
  CONTRACT_SCORE_START,
  MAX_CONTRACT_ISSUES,
  CONTRACT_DEDUCTIONS,
  ROUTE_DEFINITION_PATTERNS   as API_ROUTE_DEFINITION_PATTERNS,
  SCHEMA_VALIDATION_PATTERNS,
  VERSION_PATH_PATTERN,
  VERSION_HEADER_PATTERN,
  VERSION_QUERY_PATTERN,
  STANDARD_SUCCESS_CODES,
  STANDARD_ERROR_CODES,
  analyzeApiContract,
  analyzeApiContractMultiple,
  getLastApiContractReport,
  getApiContractReportHistory,
  resetApiContractAnalyzer,
} from "./data-and-api/api-contract-analysis/index.js";

export type {
  ComplexityIssueType,
  ComplexitySeverity,
  ComplexityPhase,
  ComplexityCodeFile,
  ComplexityIssue,
  FunctionInfo,
  CyclomaticResult,
  CognitiveResult,
  FunctionLengthResult,
  NestingDepthResult,
  IntermediateComplexityIssues,
  ComplexityReport,
  ComplexitySession,
} from "./code-quality/complexity-analysis/index.js";
export {
  COMPLEX_SCORE_START,
  MAX_COMPLEX_ISSUES,
  COMPLEX_DEDUCTIONS,
  CYCLOMATIC_THRESHOLDS,
  COGNITIVE_THRESHOLDS,
  FUNCTION_LENGTH_THRESHOLDS,
  FILE_LENGTH_THRESHOLDS,
  NESTING_THRESHOLDS,
  CYCLOMATIC_DECISION_PATTERNS,
  CONTROL_FLOW_PATTERNS,
  FUNCTION_DEF_PATTERNS,
  CALLBACK_NEST_PATTERNS,
  analyzeComplexity,
  analyzeComplexityMultiple,
  getLastComplexityReport,
  getComplexityReportHistory,
  resetComplexityAnalyzer,
} from "./code-quality/complexity-analysis/index.js";

export type {
  DeadCodeIssueType,
  DeadSeverity,
  DeadPhase,
  DeadCodeFile,
  DeadCodeIssue,
  UnusedExportsResult,
  OrphanDetectionResult,
  UnreachableCodeResult,
  IntermediateDeadIssues,
  DeadCodeReport,
  DeadCodeSession,
} from "./code-quality/dead-code-analysis/index.js";
export {
  DEAD_SCORE_START,
  MAX_DEAD_ISSUES,
  DEAD_DEDUCTIONS,
  ENTRY_POINT_PATTERNS,
  NAMED_EXPORT_PATTERNS,
  DEFAULT_EXPORT_PATTERNS,
  NAMED_EXPORT_BLOCK_PATTERN,
  IMPORT_PATTERNS,
  BARREL_EXPORT_PATTERNS,
  DEAD_CONDITIONAL_PATTERNS,
  PROCESS_EXIT_PATTERN,
  RETURN_STATEMENT_PATTERN,
  THROW_STATEMENT_PATTERN,
  UNREACHABLE_CATCH_PATTERNS,
  analyzeDeadCode,
  analyzeDeadCodeMultiple,
  getLastDeadCodeReport,
  getDeadCodeReportHistory,
  resetDeadCodeAnalyzer,
} from "./code-quality/dead-code-analysis/index.js";

export type {
  TestArchIssueType,
  TestSeverity,
  TestPhase,
  TestCodeFile,
  TestArchIssue,
  CoverageGapResult,
  LayerAnalysisResult,
  RatioAnalysisResult,
  IntermediateTestIssues,
  TestArchReport,
  TestArchSession,
} from "./testing/test-architecture-analysis/index.js";
export {
  TEST_SCORE_START,
  MAX_TEST_ISSUES,
  TEST_DEDUCTIONS,
  MIN_TEST_TO_CODE_RATIO,
  LOW_RATIO_THRESHOLD,
  TEST_FILE_PATTERNS,
  SOURCE_FILE_PATTERNS,
  SOURCE_EXCLUDE_PATTERNS,
  UNIT_TEST_PATTERNS,
  INTEGRATION_TEST_PATTERNS,
  E2E_TEST_PATTERNS,
  MOCK_PATTERNS,
  ASSERTION_PATTERNS,
  ERROR_PATH_TEST_PATTERNS,
  TEST_FRAMEWORK_PATTERNS,
  analyzeTestArchitecture,
  analyzeTestArchitectureMultiple,
  getLastTestArchReport,
  getTestArchReportHistory,
  resetTestArchAnalyzer,
} from "./testing/test-architecture-analysis/index.js";

export type {
  DbSchemaIssueType,
  DbSeverity,
  DbPhase,
  DbCodeFile,
  DbSchemaIssue,
  SchemaValidationResult,
  MigrationTrackingResult,
  OrmMisuseResult,
  IntermediateDbIssues,
  DbSchemaReport,
  DbSchemaSession,
} from "./data-and-api/database-schema-analysis/index.js";
export {
  DB_SCORE_START,
  MAX_DB_ISSUES,
  DB_DEDUCTIONS,
  PRIMARY_KEY_PATTERNS,
  FOREIGN_KEY_PATTERNS,
  INDEX_PATTERNS,
  TIMESTAMP_COLUMN_PATTERNS,
  CASCADE_PATTERNS,
  ROLLBACK_PATTERNS,
  MIGRATION_UP_PATTERNS,
  SELECT_STAR_ORM_PATTERNS,
  N1_QUERY_PATTERNS,
  TRANSACTION_PATTERNS,
  RAW_QUERY_IN_ORM_PATTERNS,
  EAGER_LOAD_PATTERNS,
  MIGRATION_FILE_PATTERNS,
  MODEL_FILE_PATTERNS,
  analyzeDbSchema,
  analyzeDbSchemaMultiple,
  getLastDbSchemaReport,
  getDbSchemaReportHistory,
  resetDbSchemaAnalyzer,
} from "./data-and-api/database-schema-analysis/index.js";

export type {
  ObservabilityIssueType,
  ObsSeverity,
  ObsPhase,
  ObsCodeFile,
  ObservabilityIssue,
  LoggingConsistencyResult,
  ErrorHandlingResult,
  MonitoringHooksResult,
  IntermediateObsIssues,
  ObservabilityReport,
  ObservabilitySession,
} from "./code-quality/observability-analysis/index.js";
export {
  OBS_SCORE_START,
  MAX_OBS_ISSUES,
  OBS_DEDUCTIONS,
  RAW_CONSOLE_PATTERNS,
  STRUCTURED_LOG_LIBRARY_PATTERNS,
  MISSING_CONTEXT_PATTERNS,
  MISSING_REQUEST_ID_PATTERNS,
  UNCAUGHT_PROMISE_PATTERNS,
  SWALLOWED_ERROR_PATTERNS,
  MISSING_ERROR_TYPE_PATTERNS,
  EMPTY_CATCH_PATTERNS,
  HEALTH_ENDPOINT_PATTERNS,
  METRICS_HOOK_PATTERNS,
  TRACE_CONTEXT_PATTERNS,
  ALERT_HOOK_PATTERNS,
  analyzeObservability,
  analyzeObservabilityMultiple,
  getLastObservabilityReport,
  getObservabilityReportHistory,
  resetObservabilityAnalyzer,
} from "./code-quality/observability-analysis/index.js";

export {
  runMasterArchitectureAnalysis,
  resetMasterOrchestrator,
} from "./orchestrator/index.js";
export type {
  MasterAnalysisInput,
  ArchitectureMasterReport,
  PhaseStatus,
} from "./orchestrator/index.js";
