/** Utilities for code text manipulation used by generators. */

export function fileHeader(description: string): string {
  return `/**\n * ${description}\n * Auto-generated by Executor Agent\n */\n\n`;
}

export function normalizeIndent(code: string, spaces = 2): string {
  const lines = code.split('\n');
  const indent = ' '.repeat(spaces);
  return lines
    .map((line) => (line.trim() === '' ? '' : indent + line.trimStart()))
    .join('\n');
}

export function wrapInTryCatch(body: string, errorVar = 'err'): string {
  return `try {\n${body}\n} catch (${errorVar}) {\n  throw ${errorVar};\n}`;
}

export function toCamelCase(str: string): string {
  return str
    .replace(/[-_\s](.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (c) => c.toLowerCase());
}

export function toPascalCase(str: string): string {
  const camel = toCamelCase(str);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

export function toKebabCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '-$1')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
    .replace(/^-/, '');
}

export function isTypeScriptFile(filePath: string): boolean {
  return filePath.endsWith('.ts') || filePath.endsWith('.tsx');
}

export function isJavaScriptFile(filePath: string): boolean {
  return filePath.endsWith('.js') || filePath.endsWith('.jsx');
}

export function getFileExtension(filePath: string): string {
  const dot = filePath.lastIndexOf('.');
  return dot >= 0 ? filePath.slice(dot) : '';
}

export function joinLines(...lines: string[]): string {
  return lines.join('\n');
}

export function indentBlock(code: string, levels = 1): string {
  const pad = '  '.repeat(levels);
  return code
    .split('\n')
    .map((l) => (l.trim() === '' ? '' : `${pad}${l}`))
    .join('\n');
}
